headersOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/Users/nivshimoni/Desktop/Discover LT"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/*"

[headers.values]
Cache-Control = "public, max-age=3600"

[[headers]]
for = "/region-images.js"

[headers.values]
Cache-Control = "public, max-age=86400"

[[headers]]
for = "/data.js"

[headers.values]
Cache-Control = "public, max-age=3600"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]