// Travel data for Lithuania discovery app — merged with Niv's curated places
// Bilingual content (he + en)
window._DL_DATA_VERSION = '20260707o';

(function() {

// 6 regions matching Niv's cities
const REGIONS = [
  {
    id: 'vilnius',
    he: { name: 'וילנה', tag: 'בירת הברוק', blurb: 'סמטאות אבן, גגות אדומים, ובתי קפה בכל פינה. רפובליקת אוז\'ופיס האמנותית מעבר לנהר.' },
    en: { name: 'Vilnius', tag: 'Baroque Capital', blurb: 'Cobbled lanes, terracotta roofs, and a café on every corner. Užupis art republic just across the river.' },
    accent: '#C28840',
    placeholder: 'Old Town rooftops at golden hour'
  },
  {
    id: 'trakai',
    he: { name: 'טראקאי', tag: 'טירה על אגם', blurb: 'טירת האבן היחידה בליטא שנותרה על אי באגם גלווה. עיירת הקראים, סירות צבעוניות, וקיביני טריים מהתנור.' },
    en: { name: 'Trakai', tag: 'Castle on the Lake', blurb: "Lithuania's only island castle, rising from Lake Galvė. Karaim heritage, colorful boats, and fresh kibinai straight from the oven." },
    accent: '#5C8AA6',
    placeholder: 'Trakai Island Castle reflected in Lake Galvė at golden hour'
  },
  {
    id: 'kaunas',
    he: { name: 'קובנה', tag: 'מודרניזם בין-מלחמתי', blurb: 'בירת הארץ לשעבר, יער של ארכיטקטורת באוהאוס וסצנת קפה צעירה ותוססת.' },
    en: { name: 'Kaunas', tag: 'Interwar Modernism', blurb: 'The former capital — a forest of Bauhaus façades and a young, buzzing café scene.' },
    accent: '#7E6A4E',
    placeholder: 'Laisvės Alėja boulevard'
  },
  {
    id: 'klaipeda',
    he: { name: 'קלייפדה', tag: 'נמל וים בלטי', blurb: 'הים הקר, ענבר על החוף, ושוקי דגים בעיר נמל גרמנית-לשעבר.' },
    en: { name: 'Klaipėda', tag: 'Port & Baltic Sea', blurb: 'Cold sea breeze, amber on the shoreline, fish markets in a once-Prussian port city.' },
    accent: '#4A7C8C',
    placeholder: 'Wooden pier at the Baltic'
  },
  {
    id: 'curonian',
    he: { name: 'רכס קורון (נידה)', tag: 'דיונות וצנובר', blurb: 'דיונות ענק במורד החצי-אי הצר, יערות אורנים, וכפרי דייגים צבעוניים.' },
    en: { name: 'Curonian Spit (Nida)', tag: 'Dunes & Pine', blurb: 'Giant dunes down a narrow peninsula, pine forests, and pastel fishing villages.' },
    accent: '#B89968',
    placeholder: 'Parnidis dune ridge'
  },
  {
    id: 'countryside',
    he: { name: 'הכפר', tag: 'יערות, אגמים, סאונה', blurb: 'בקתות עץ ביער, אגמים בתוליים, גלמפינג ופירטיס מסורתי.' },
    en: { name: 'Countryside', tag: 'Forest · Lakes · Sauna', blurb: 'Forest cabins, virgin lakes, glamping and traditional pirtis sauna.' },
    accent: '#5F7A4A',
    placeholder: 'Forest cabin and lake'
  },
  {
    id: 'druskininkai',
    he: { name: 'דרוסקיניינקאי', tag: 'ספא ואגמים מרפאים', blurb: 'עיירת ספא דרומית עם מעיינות מינרליים, יערות אורן, וחופשה כיף לסופ\'ש.' },
    en: { name: 'Druskininkai', tag: 'Spa & Healing Lakes', blurb: 'Southern spa town with mineral springs, pine forests, and a perfect weekend escape.' },
    accent: '#A85D4A',
    placeholder: 'Spa resort by the lake'
  },
  {
    id: 'palanga',
    he: { name: 'פלאנגה', tag: 'עיירת חוף וענבר', blurb: 'עיירת נופש קלאסית על הים הבלטי, עם טיילת ארוכה, מוזיאון הענבר, וגן בוטני מרהיב.' },
    en: { name: 'Palanga', tag: 'Beach Town & Amber', blurb: 'A classic Baltic seaside resort with a long pier, the Amber Museum, and a stunning botanical garden.' },
    accent: '#D4A05A',
    placeholder: 'Wooden pier into the Baltic'
  },
  {
    id: 'moletai',
    he: { name: 'מולטאי', tag: 'בירת האסטרונומיה', blurb: 'עיירה שלווה בלב מחוז האגמים — האובסרבטוריה הליטאית ושמיים בלי זיהום אור.' },
    en: { name: 'Molėtai', tag: 'Astronomy Capital', blurb: 'A quiet town in the heart of lake country — home to the national observatory and dark skies.' },
    accent: '#4A6B7E',
    placeholder: 'Lake and pine forest'
  },
  {
    id: 'zarasai',
    he: { name: 'זרסאי', tag: 'עיר חמשת האגמים', blurb: 'עיירה רומנטית על אי בין חמישה אגמים, ממש על הגבול הצפון-מזרחי.' },
    en: { name: 'Zarasai', tag: 'Town of Five Lakes', blurb: 'A romantic town on an island between five lakes, on the northeastern border.' },
    accent: '#5A8A8A',
    placeholder: 'Boardwalk over the lake'
  }
];

// Niv's curated places — 77 spots from his Google Maps
const PLACES = [
  {
    "id": "kalve-coffee-vasario",
    "region": "vilnius",
    "kind": "cafe",
    "name": "KALVE Coffee Vasario",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.5,
    "reviews": 141,
    "price": "€5–10",
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "rocketbean-kavin",
    "region": "vilnius",
    "kind": "cafe",
    "name": "RocketBean Kavinė",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.9,
    "reviews": 275,
    "price": "€5–10",
    "emoji": "🚀",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "yugen-tea",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Yugen Tea",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.9,
    "reviews": 341,
    "price": "€5–10",
    "emoji": "🍵",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "espresin",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Espresinė",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.9,
    "reviews": 399,
    "price": "€5–10",
    "emoji": "☕",
    "niv": "Tiny espresso bar with seriously good coffee. Local favorite.",
    "nivHe": "בר אספרסו זעיר עם קפה ברמה רצינית. מקום מועדף על המקומיים.",
    "mapUrl": "https://maps.app.goo.gl/L7yNZbDcwaEXpk8S9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "mon",
    "region": "vilnius",
    "kind": "cafe",
    "name": "mon.",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.7,
    "reviews": 366,
    "price": "€10–15",
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "strangelove",
    "region": "vilnius",
    "kind": "cafe",
    "name": "StrangeLove",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.5,
    "reviews": 1375,
    "price": "€5–10",
    "emoji": "🖤",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "coffee-circus-piano",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Coffee Circus Piano",
    "type": "Cafeteria",
    "typeHe": "בית קפה",
    "rating": 4.7,
    "reviews": 483,
    "price": "€5–10",
    "emoji": "🎪",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "brew-specialty-coffee",
    "region": "vilnius",
    "kind": "cafe",
    "name": "BREW. Specialty Coffee",
    "type": "Bakery",
    "typeHe": "מאפייה",
    "rating": 4.6,
    "reviews": 333,
    "price": "€5–10",
    "emoji": "🥐",
    "niv": "Specialty roaster with excellent pastries — perfect morning stop.",
    "nivHe": "קלייה ספשלטי עם מאפים מעולים — עצירת בוקר מושלמת.",
    "mapUrl": "https://maps.app.goo.gl/3oA2cV61rYqw5gZNA",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "art-cafe",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Art Cafe",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.7,
    "reviews": 142,
    "price": "€5–10",
    "emoji": "🎨",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "beigelistai",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Beigelistai",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.6,
    "reviews": 1173,
    "price": "€5–10",
    "emoji": "🥯",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "backstage-roastery-caf",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Backstage Roastery Café",
    "type": "Breakfast",
    "typeHe": "ארוחת בוקר",
    "rating": 4.5,
    "reviews": 911,
    "price": "€10–15",
    "emoji": "🥞",
    "niv": "One of the best brunch spots in Vilnius — always packed, always worth it.",
    "nivHe": "אחד הברנצ'ים הכי טובים בווילנה — תמיד מלא, תמיד שווה.",
    "mapUrl": "https://www.google.com/maps?q=54.6747985,25.2660406",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "backstage-cafe-vokie-i-str",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Backstage Cafe Vokiečių str.",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.1,
    "reviews": 618,
    "price": "€5–15",
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "italala-caff",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Italala Caffè",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.7,
    "reviews": 1435,
    "price": "€5–10",
    "emoji": "🇮🇹",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "lola",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Lola",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.4,
    "reviews": 1036,
    "price": "€10–15",
    "emoji": "🌸",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "barn-bistro-b-arn",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "BARN bistro (B'ARN)",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.9,
    "reviews": 144,
    "price": "€50+",
    "emoji": "🥩",
    "niv": "Top-end dining — extraordinary quality.",
    "nivHe": "ארוחה ברמה הכי גבוהה — איכות יוצאת דופן.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "tempo-v39",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Tempo V39",
    "type": "Bistro",
    "typeHe": "ביסטרו",
    "rating": 4.7,
    "reviews": 230,
    "price": "€25–50",
    "emoji": "🍷",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "pachamama-dinner-club",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Pachamama Dinner Club",
    "type": "Peruvian",
    "typeHe": "פרואנית",
    "rating": 4.6,
    "reviews": 1687,
    "price": "€50+",
    "emoji": "🇵🇪",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "meat-steakhouse",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Meat SteakHouse",
    "type": "Steak",
    "typeHe": "סטייקיה",
    "rating": 4.4,
    "reviews": 1570,
    "price": "€50+",
    "emoji": "🥩",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "cha-apuri",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Chačapuri",
    "type": "Georgian",
    "typeHe": "גאורגית",
    "rating": 4.7,
    "reviews": 2683,
    "price": "€10–15",
    "emoji": "🧀",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "focacceria",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Focacceria",
    "type": "Sandwich",
    "typeHe": "כריכים",
    "rating": 5,
    "reviews": 52,
    "price": "€5–10",
    "emoji": "🥪",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "baleboste",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Baleboste",
    "type": "Jewish",
    "typeHe": "יהודית",
    "rating": 4.5,
    "reviews": 410,
    "price": "€10–15",
    "emoji": "✡️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "le-travi",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Le Travi",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.6,
    "reviews": 536,
    "price": "€20–45",
    "emoji": "🍝",
    "niv": "Cozy Italian bistro — great pasta and intimate atmosphere.",
    "nivHe": "ביסטרו איטלקי חמימות — פסטה מעולה ואווירה אינטימית.",
    "mapUrl": "https://maps.app.goo.gl/jdVee8KgtKYz238f7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "donde",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Donde",
    "type": "Tex Mex",
    "typeHe": "טקס-מקס",
    "rating": 4.7,
    "reviews": 877,
    "price": "€10–15",
    "emoji": "🌮",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "mason-restoranas",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Mason Restoranas",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.5,
    "reviews": 511,
    "price": "€15–45",
    "emoji": "🍴",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "2-vir-jai",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "2 virėjai",
    "type": "Lithuanian lunch",
    "typeHe": "צהריים ליטאיים",
    "rating": 5,
    "reviews": 75,
    "price": "€10–15",
    "emoji": "👨‍🍳",
    "niv": "A tiny lunch spot run by two local cooks. Perfect rating, no tourists, honest Lithuanian food. Exactly what you want in the middle of a Vilnius day.",
    "nivHe": "מקום צהריים קטן של שני שפים מקומיים. דירוג מושלם, בלי תיירים, אוכל ליטאי אמיתי. בדיוק מה שצריך באמצע יום בווילנה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "bistro-n-2",
    "region": "vilnius",
    "kind": "restaurant",
    "name": "Bistro n.2",
    "type": "Bistro",
    "typeHe": "ביסטרו",
    "rating": 4.6,
    "reviews": 221,
    "price": null,
    "emoji": "🍽️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "naked-noah",
    "region": "vilnius",
    "kind": "market",
    "name": "Naked Noah",
    "type": "Wine store",
    "typeHe": "יין",
    "rating": 4.8,
    "reviews": 57,
    "price": null,
    "emoji": "🍷",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "burbulio-vynin",
    "region": "vilnius",
    "kind": "market",
    "name": "Burbulio Vyninė",
    "type": "Wine store",
    "typeHe": "יין",
    "rating": 4.8,
    "reviews": 435,
    "price": null,
    "emoji": "🍾",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "la-madeleine-atelier",
    "region": "vilnius",
    "kind": "cafe",
    "name": "La Madeleine Atelier",
    "type": "Pastries",
    "typeHe": "מאפים",
    "rating": 4.8,
    "reviews": 53,
    "price": null,
    "emoji": "🥐",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "mindaugo-kepykla",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Mindaugo kepykla",
    "type": "Patisserie",
    "typeHe": "פטיסרי",
    "rating": 4.7,
    "reviews": 221,
    "price": null,
    "emoji": "🥐",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "desert-klubas",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Desertų klubas",
    "type": "Bakery",
    "typeHe": "מאפייה",
    "rating": 4.4,
    "reviews": 214,
    "price": "€5–15",
    "emoji": "🎂",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "bundu",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Bundu",
    "type": "Bakery",
    "typeHe": "מאפייה",
    "rating": 4.8,
    "reviews": 255,
    "price": "€5–10",
    "emoji": "🍞",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "adata-bar",
    "region": "vilnius",
    "kind": "market",
    "name": "Adata Bar",
    "type": "Bar",
    "typeHe": "בר",
    "rating": 4.6,
    "reviews": 78,
    "price": "€10–30",
    "emoji": "🍸",
    "niv": "Intimate cocktail bar with creative drinks. Reserve a seat.",
    "nivHe": "בר קוקטיילים אינטימי עם שתייה יצירתית. כדאי להזמין מקום.",
    "mapUrl": "https://maps.app.goo.gl/sKGGPa3UoayEPEDB6",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "paupio-turgus",
    "region": "vilnius",
    "kind": "market",
    "name": "Paupio Turgus",
    "type": "Food court",
    "typeHe": "שוק אוכל",
    "rating": 4.6,
    "reviews": 3969,
    "price": "€10–15",
    "emoji": "🛒",
    "niv": "Best food market in Vilnius — go on Saturday morning.",
    "nivHe": "השוק הכי טוב בווילנה — שווה ללכת בשבת בבוקר.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "benedikto-turgus",
    "region": "vilnius",
    "kind": "market",
    "name": "Benedikto Turgus",
    "type": "Farmers market",
    "typeHe": "שוק איכרים",
    "rating": 4.4,
    "reviews": 2414,
    "price": null,
    "emoji": "🥕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "3m-zos-rooftop-bar",
    "region": "vilnius",
    "kind": "market",
    "name": "3Mūzos Rooftop Bar",
    "type": "Bar",
    "typeHe": "בר",
    "rating": 4.1,
    "reviews": 198,
    "price": "€10–25",
    "emoji": "🌆",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "po-ba-ka",
    "region": "vilnius",
    "kind": "market",
    "name": "Po bačka",
    "type": "Bar",
    "typeHe": "בר",
    "rating": 4.8,
    "reviews": 53,
    "price": "€1–5",
    "emoji": "🍺",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "mo-museum",
    "region": "vilnius",
    "kind": "culture",
    "name": "MO Museum",
    "type": "Modern art museum",
    "typeHe": "מוזיאון",
    "rating": 4.5,
    "reviews": 7195,
    "price": null,
    "emoji": "🎨",
    "niv": "World-class modern art museum — don't miss it.",
    "nivHe": "מוזיאון אמנות מודרנית ברמה עולמית — לא לפספס.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "men-fabrikas-loftas",
    "region": "vilnius",
    "kind": "culture",
    "name": "Menų fabrikas Loftas",
    "type": "Cultural center",
    "typeHe": "מרכז תרבות",
    "rating": 4.5,
    "reviews": 3128,
    "price": null,
    "emoji": "🏭",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "the-green-house",
    "region": "vilnius",
    "kind": "culture",
    "name": "The Green House",
    "type": "Museum",
    "typeHe": "מוזיאון",
    "rating": 4.5,
    "reviews": 397,
    "price": null,
    "emoji": "🟢",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "gediminas-castle",
    "region": "vilnius",
    "kind": "culture",
    "name": "Gediminas Castle",
    "type": "History museum",
    "typeHe": "מוזיאון",
    "rating": 4.7,
    "reviews": 12766,
    "price": null,
    "emoji": "🏰",
    "niv": "Fantastic view of Vilnius — come at sunset for the golden hour. Watch hot-air balloons in the morning.",
    "nivHe": "נוף מטריף על וילנה — בואו בשקיעה לשעת הזהב. בבוקר אפשר לראות כדורים פורחים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "atvira-meno-galerija",
    "region": "vilnius",
    "kind": "culture",
    "name": "Atvira meno galerija",
    "type": "Art gallery",
    "typeHe": "גלריה",
    "rating": 4.6,
    "reviews": 106,
    "price": null,
    "emoji": "🖼️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "backstage-roastery-hq",
    "region": "vilnius",
    "kind": "cafe",
    "name": "Backstage Roastery HQ",
    "type": "Coffee roastery",
    "typeHe": "קלייה",
    "rating": 4.2,
    "reviews": 17,
    "price": null,
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "snapas-kava-ir-desertai",
    "region": "trakai",
    "kind": "cafe",
    "name": "Snapas Kava ir Desertai",
    "type": "Specialty coffee & bakery",
    "typeHe": "בית קפה ומאפייה",
    "rating": 4.7,
    "reviews": 155,
    "price": "€5–10",
    "emoji": "☕",
    "niv": "A tiny café on Vytauto Street that a local woman, Laima, opened herself after years of failing to find a proper cup of coffee in Trakai — now it's the warmest corner in town, with single-origin coffee, fresh-baked croissants and brownies every morning, and homemade treats from her own honeyberry orchard.",
    "nivHe": "בית קפה קטן ברחוב ויטאוטו שלאימה, תושבת מקומית, פתחה בעצמה אחרי שנים שלא הצליחה למצוא כוס קפה הגונה בטראקאי — היום זה הפינה הכי חמימה בעיר: קפה איכותי, קרואסונים ובראוניז שנאפים טריים כל בוקר, וממתקים ביתיים מהגינה שלה עם פירות יער sausmedis.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "b-heme-house",
    "region": "kaunas",
    "kind": "restaurant",
    "name": "BōHEME HOUSE",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.2,
    "reviews": 289,
    "price": null,
    "emoji": "🎭",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "habits-bakery",
    "region": "kaunas",
    "kind": "cafe",
    "name": "Habits Bakery",
    "type": "Bakery",
    "typeHe": "מאפייה",
    "rating": 4.4,
    "reviews": 790,
    "price": "€10–15",
    "emoji": "🍞",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "nyc-coffee-co",
    "region": "kaunas",
    "kind": "cafe",
    "name": "NYC Coffee Co.",
    "type": "Cafe",
    "typeHe": "בית קפה",
    "rating": 4.9,
    "reviews": 363,
    "price": "€1–5",
    "emoji": "🗽",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kavos-architektai",
    "region": "klaipeda",
    "kind": "cafe",
    "name": "Kavos architektai",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.7,
    "reviews": 937,
    "price": "€5–10",
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "klaip-dos-yd-bendruomen",
    "region": "klaipeda",
    "kind": "culture",
    "name": "Klaipėda Jewish Community",
    "type": "Jewish heritage site",
    "typeHe": "אתר מורשת יהודית",
    "rating": 5,
    "reviews": 6,
    "price": null,
    "emoji": "✡️",
    "niv": "A small but meaningful Jewish presence in Klaipėda — one of the few remaining connections to the once-thriving Jewish community of this port city. Worth a visit if you're in the area.",
    "nivHe": "נוכחות יהודית קטנה אך משמעותית בקלייפדה — אחד מהקשרים הנותרים לקהילה היהודית השוקקת שפרחה פעם בעיר נמל זו. שווה ביקור אם אתם באזור.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "muskatas",
    "region": "klaipeda",
    "kind": "restaurant",
    "name": "Muskatas",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.5,
    "reviews": 338,
    "price": null,
    "emoji": "🌿",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "bistro-zarasai",
    "region": "zarasai",
    "kind": "restaurant",
    "name": "Bistro Zarasai",
    "type": "Fast food",
    "typeHe": "אוכל מהיר",
    "rating": 4.5,
    "reviews": 72,
    "price": "€10–20",
    "emoji": "🍔",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "spricas-brunch-2",
    "region": "klaipeda",
    "kind": "cafe",
    "name": "Spricas Brunch",
    "type": "Breakfast",
    "typeHe": "ארוחת בוקר",
    "rating": 4.9,
    "reviews": 452,
    "price": "€10–15",
    "emoji": "🥞",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "the-dead-dunes",
    "region": "curonian",
    "kind": "nature",
    "name": "The Dead Dunes",
    "type": "Tourist attraction",
    "typeHe": "אטרקציה",
    "rating": 4.8,
    "reviews": 2503,
    "price": null,
    "emoji": "🏜️",
    "niv": "Magical UNESCO landscape — the sand dunes are unlike anything in Europe.",
    "nivHe": "נוף קסום של אונסק\"ו — דיונות חול שאין כמותן באירופה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "vecekrugas-dune",
    "region": "curonian",
    "kind": "nature",
    "name": "Vecekrugas Dune",
    "type": "Nature preserve",
    "typeHe": "שמורת טבע",
    "rating": 4.9,
    "reviews": 806,
    "price": null,
    "emoji": "🏔️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "smoked-fish",
    "region": "curonian",
    "kind": "restaurant",
    "name": "Smoked fish",
    "type": "Fish store",
    "typeHe": "דגים מעושנים",
    "rating": 4.9,
    "reviews": 64,
    "price": null,
    "emoji": "🐟",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "mi-ko-rojus",
    "region": "countryside",
    "kind": "stay",
    "name": "Miško Rojus",
    "type": "Accommodation",
    "typeHe": "לינה",
    "rating": 4.5,
    "reviews": 45,
    "price": null,
    "emoji": "🏡",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "doyou-place",
    "region": "countryside",
    "kind": "stay",
    "name": "DOYOU PLACE",
    "type": "Holiday apartment",
    "typeHe": "דירת נופש",
    "rating": 4.8,
    "reviews": 154,
    "price": null,
    "emoji": "🌲",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "pami-k-boutique-spa",
    "region": "palanga",
    "kind": "stay",
    "name": "PAMIŠKĖ BOUTIQUE SPA",
    "type": "Forest Cabin & Sauna",
    "typeHe": "קתת ביער וסאונה",
    "rating": 5,
    "reviews": 21,
    "price": null,
    "emoji": "🛖",
    "niv": "Not a hotel — a private forest cabin with a real Lithuanian sauna and outdoor wooden tub. You rent the whole place, just for yourself.",
    "nivHe": "לא מלון — קתת ביער פרטית עם סאונה ליטאית אמיתית ואמבט עץ בחוץ. שוכרים את כל המקום לעצמך בלבד.",
    "mapUrl": "https://www.google.com/maps/place/PAMI%C5%A0K%C4%96+BOUTIQUE+SPA/@55.8358834,21.3534571,17z",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "casa-de-campo-glamping-lithuania",
    "region": "countryside",
    "kind": "stay",
    "name": "casa de campo glamping Lithuania",
    "type": "Camping farm",
    "typeHe": "גלמפינג",
    "rating": 5,
    "reviews": 183,
    "price": null,
    "emoji": "⛺",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "hytte",
    "region": "countryside",
    "kind": "stay",
    "name": "HYTTE",
    "type": "Holiday home",
    "typeHe": "בית נופש",
    "rating": 4.9,
    "reviews": 118,
    "price": null,
    "emoji": "🏠",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "alantos-irgai-sodybos-ir-nameli",
    "region": "moletai",
    "kind": "stay",
    "name": "Alantos Žirgai - Sodybos ir namelių…",
    "type": "Holiday home",
    "typeHe": "בית נופש",
    "rating": 4.9,
    "reviews": 139,
    "price": null,
    "emoji": "🐴",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "villa-the-lake",
    "region": "moletai",
    "kind": "stay",
    "name": "Villa The Lake",
    "type": "Villa",
    "typeHe": "וילה",
    "rating": 5,
    "reviews": 28,
    "price": null,
    "emoji": "🏡",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kupetait",
    "region": "countryside",
    "kind": "stay",
    "name": "Kupetaitė",
    "type": "Holiday apartment",
    "typeHe": "דירת נופש",
    "rating": 4.9,
    "reviews": 18,
    "price": null,
    "emoji": "🌿",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "getaway-to-forest-cab",
    "region": "countryside",
    "kind": "stay",
    "name": "Getaway to forest cab",
    "type": "Lodging",
    "typeHe": "לינה",
    "rating": 4.9,
    "reviews": 37,
    "price": null,
    "emoji": "🪵",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "www-pineplace-lt",
    "region": "moletai",
    "kind": "stay",
    "name": "www.pineplace.lt",
    "type": "Holiday apartment",
    "typeHe": "דירת נופש",
    "rating": 4.3,
    "reviews": 42,
    "price": null,
    "emoji": "🌲",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "atvira-meno-galerija-open-gallery",
    "region": "vilnius",
    "kind": "culture",
    "name": "Atvira meno galerija (open gallery)",
    "type": "Art gallery",
    "typeHe": "גלריה",
    "rating": 4.6,
    "reviews": 106,
    "price": null,
    "emoji": "🖼️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "mana-sleep-spa-druskininkai",
    "region": "druskininkai",
    "kind": "stay",
    "name": "Mana Sleep & Spa | Druskininkai",
    "type": "5-star hotel",
    "typeHe": "מלון 5 כוכבים",
    "rating": 4.7,
    "reviews": 196,
    "price": null,
    "emoji": "💆",
    "niv": "Best spa resort in Lithuania — pure relaxation.",
    "nivHe": "ספא-ריזורט הכי טוב בליטא — רגיעה צרופה.",
    "mapUrl": "https://maps.app.goo.gl/e5ynZktiUyr2tGt76",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "la-petite-france-vilnius",
    "region": "vilnius",
    "kind": "cafe",
    "name": "La petite France Vilnius",
    "type": "Café",
    "typeHe": "בית קפה",
    "rating": 4.9,
    "reviews": 119,
    "price": null,
    "emoji": "🥐",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "hotel-pacai",
    "region": "vilnius",
    "kind": "stay",
    "name": "Hotel PACAI",
    "type": "5-star boutique hotel in a baroque palace",
    "typeHe": "מלון בוטיק 5 כוכבים בארמון בארוקי",
    "rating": 4.8,
    "reviews": 1308,
    "price": null,
    "emoji": "🏛️",
    "niv": "The most stunning hotel in Vilnius — a 17th-century baroque palace turned into a world-class boutique hotel, right in the Old Town. Every corner is a work of art. If you're going to splurge once in Lithuania, this is it.",
    "nivHe": "המלון המרהיב ביותר בווילנה — ארמון בארוקי מהמאה ה-17 שהפך למלון בוטיק ברמה עולמית, ממש בלב העיר העתיקה. כל פינה היא יצירת אמנות. אם פעם אחת מותר לבזבז בליטא — זה המקום.",
    "mapUrl": "https://maps.app.goo.gl/1W6EqKYWEzCzoqu86",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "neringa-hotel",
    "region": "vilnius",
    "kind": "stay",
    "name": "Neringa Hotel",
    "type": "4-star hotel on Gediminas Avenue",
    "typeHe": "מלון 4 כוכבים על שדרת גדימינס",
    "rating": 4.5,
    "reviews": 1696,
    "price": null,
    "emoji": "🌆",
    "niv": "My go-to hotel in Vilnius — perfectly located on Gediminas Avenue, the main boulevard of the city. Beautiful rooms, great breakfast, fantastic rooftop bar with panoramic city views. The staff goes above and beyond. If you want to be close to everything, this is the place.",
    "nivHe": "המלון שאני חוזר אליו בווילנה — מיקום מושלם על שדרת גדימינס, הבולוואר הראשי של העיר. חדרים יפים, ארוחת בוקר מצוינת, בר גג פנטסטי עם נוף פנורמי. הצוות יוצא מגדרו. אם אתם רוצים להיות קרוב לכל דבר — זה המקום.",
    "mapUrl": "https://maps.app.goo.gl/7XUbSgV2z6EH5NZC8",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "comfort-hotel-vilnius",
    "region": "vilnius",
    "kind": "stay",
    "name": "Comfort Hotel LT – Rock 'n' Roll Vilnius",
    "type": "3-star music-themed hotel",
    "typeHe": "מלון 3 כוכבים בסגנון רוק אנד רול",
    "rating": 4.6,
    "reviews": 3428,
    "price": null,
    "emoji": "🎸",
    "niv": "A fun, music-themed 3-star hotel with great value and an excellent location. One of the highest-rated budget hotels in Vilnius — clean, comfortable, and full of personality.",
    "nivHe": "מלון 3 כוכבים מבדר בסגנון מוזיקלי עם ערך מצוין ומיקום טוב. אחד ממלוני הבאדג'ט המדורגים הכי גבוה בווילנה — נקי, נוח ועם אופי.",
    "mapUrl": "https://maps.app.goo.gl/SqkDDRjFc8EueN3u7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "radisson-blu-lietuva",
    "region": "vilnius",
    "kind": "stay",
    "name": "Radisson Blu Hotel Lietuva",
    "type": "4-star high-rise with spa & skybar",
    "typeHe": "מלון 4 כוכבים עם ספא ובר גג",
    "rating": 4.6,
    "reviews": 5185,
    "price": null,
    "emoji": "🏙️",
    "niv": "A large, polished 4-star hotel with one of the best spas in the city and the legendary Skybar on the top floor — incredible views over the river and city skyline. Great for business travelers or anyone who wants a full-service hotel experience.",
    "nivHe": "מלון 4 כוכבים גדול ומשופשף עם אחד הספאים הטובים בעיר וה-Skybar האגדי בקומה העליונה — נוף עוצר נשימה על הנהר והאופק העירוני. מצוין לנוסעי עסקים או למי שרוצה חוויית מלון מלאה.",
    "mapUrl": "https://maps.app.goo.gl/d9ozfT6WhHyoJJCr9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "ac-hotel-vilnius",
    "region": "vilnius",
    "kind": "stay",
    "name": "AC Hotel Vilnius",
    "type": "4-star Marriott hotel in the city centre",
    "typeHe": "מלון מריוט 4 כוכבים במרכז העיר",
    "rating": 4.6,
    "reviews": 188,
    "price": null,
    "emoji": "🏨",
    "niv": "A beautiful, modern hotel in the heart of Vilnius — spacious, with an impressive elegant lobby that makes a great first impression. Comfortable well-designed rooms, and an excellent varied breakfast. Perfect for a business trip or a polished city stay.",
    "nivHe": "מלון יפה ומודרני בלב וילנה — מרווח, עם לובי אלגנטי ומרשים שיוצר רושם ראשוני נהדר. חדרים נוחים ומעוצבים, וארוחת בוקר מצוינת ומגוונת. מושלם לנסיעת עסקים או לשהייה עירונית מסוגננת.",
    "mapUrl": "https://maps.app.goo.gl/9FFAt2SRnEnZJUuF9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "rooma-apartments-vilnius",
    "region": "vilnius",
    "kind": "stay",
    "name": "ROOMA Apartments Vilnius",
    "type": "Boutique apartments",
    "typeHe": "דירות בוטיק",
    "rating": 4.9,
    "reviews": 62,
    "price": null,
    "emoji": "🏠",
    "niv": "Gorgeous boutique apartments right in the heart of Vilnius Old Town — walking distance from all the main attractions. Stylish, cosy and immaculately clean.",
    "nivHe": "דירות בוטיק מדהימות ממש במרכז העיר העתיקה של וילנה — רגלית מכל האטרקציות המרכזיות. מעוצבות, חמימות ונקיות ברמה גבוהה.",
    "mapUrl": "https://maps.app.goo.gl/qw2psfqTiLykisid9",
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "brut-wine-restaurant-zarasai",
    "region": "zarasai",
    "kind": "restaurant",
    "name": "Brut Wine Hotel & Restaurant",
    "type": "Wine restaurant",
    "typeHe": "מסעדת יין",
    "rating": 4.6,
    "reviews": 118,
    "price": "€25–50",
    "emoji": "🍷",
    "niv": "Charcoal-grilled meats and an excellent wine list — the most stylish dinner in Zarasai.",
    "nivHe": "בשרים על פחם ורשימת יין מצוינת — הארוחה הכי סטייל בזרסאי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "monopolis-zarasai",
    "region": "zarasai",
    "kind": "restaurant",
    "name": "Monopolis",
    "type": "Lake-view restaurant",
    "typeHe": "מסעדה עם נוף לאגם",
    "rating": 4.4,
    "reviews": 72,
    "price": "€15–30",
    "emoji": "🐟",
    "niv": "Lakeside terrace and locally-caught vendace — the rarest fish dish in northeastern Lithuania.",
    "nivHe": "טרסה על האגם עם דג ונדאס מקומי — המנה הנדירה ביותר בצפון-מזרח ליטא.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "lietaus-sodai",
    "region": "zarasai",
    "kind": "market",
    "name": "Lietaus Sodai",
    "type": "Shop-café",
    "typeHe": "קפה-חנות",
    "rating": 4.6,
    "reviews": 292,
    "price": "€5–15",
    "emoji": "🛒",
    "niv": "Part gourmet deli, part café — local wines, artisan cheeses, and homemade desserts under one roof.",
    "nivHe": "חצי דלי גורמה, חצי קפה — יינות מקומיים, גבינות אומן ומתוקים ביתיים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "zarasai-five-lakes",
    "region": "zarasai",
    "kind": "nature",
    "name": "The Five Lakes of Zarasai",
    "type": "Lake district",
    "typeHe": "אזור חמשת האגמים",
    "rating": 4.8,
    "reviews": 340,
    "price": null,
    "emoji": "🌊",
    "niv": "The town sits on a peninsula between five interconnected lakes — kayak, swim, or just watch the light change.",
    "nivHe": "העיר יושבת על חצי-אי בין חמישה אגמים מחוברים — קיאקים, שחייה, או פשוט לצפות באור משתנה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "sartai-lake",
    "region": "zarasai",
    "kind": "nature",
    "name": "Lake Sartai",
    "type": "Lake",
    "typeHe": "אגם",
    "rating": 4.8,
    "reviews": 380,
    "price": null,
    "emoji": "🧊",
    "niv": "Lithuania's famous ice-yachting lake in winter, crystal-clear swimming in summer. Unforgettable in any season.",
    "nivHe": "אגם השיט על הקרח המפורסם של ליטא בחורף, שחייה קריסטלית בקיץ. בלתי נשכח בכל עונה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "zarasai-museum",
    "region": "zarasai",
    "kind": "culture",
    "name": "Zarasai Regional Museum",
    "type": "History museum",
    "typeHe": "מוזיאון אזורי",
    "rating": 4.4,
    "reviews": 95,
    "price": null,
    "emoji": "🏛️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "zarasai-promenade",
    "region": "zarasai",
    "kind": "nature",
    "name": "Zarasai Lake Promenade",
    "type": "Lakeside walk",
    "typeHe": "טיילת אגם",
    "rating": 4.6,
    "reviews": 220,
    "price": null,
    "emoji": "🚶",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kemping-zarasai",
    "region": "zarasai",
    "kind": "stay",
    "name": "Zarasai Camping & Leisure",
    "type": "Lakeside camping",
    "typeHe": "קמפינג על האגם",
    "rating": 4.4,
    "reviews": 85,
    "price": null,
    "emoji": "⛺",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "palanga-amber-museum",
    "region": "palanga",
    "kind": "culture",
    "name": "Palanga Amber Museum",
    "type": "Museum",
    "typeHe": "מוזיאון הענבר",
    "rating": 4.6,
    "reviews": 4820,
    "price": null,
    "emoji": "🟡",
    "niv": "28,000 pieces of amber — including prehistoric insects frozen in time — in a grand 19th-century palace.",
    "nivHe": "28,000 פריטי ענבר כולל חרקים פרהיסטוריים קפואים בזמן — בארמון מהמאה ה-19.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "birute-park-palanga",
    "region": "palanga",
    "kind": "nature",
    "name": "Birutė Park",
    "type": "Botanical garden",
    "typeHe": "גן בוטני",
    "rating": 4.7,
    "reviews": 2180,
    "price": null,
    "emoji": "🌹",
    "niv": "100 hectares of sculpted grounds — rose gardens, ancient dunes, summer concerts. Free to enter.",
    "nivHe": "100 דונם של גנים מעוצבים — גני ורדים, דיונות עתיקות וקונצרטים בקיץ. כניסה חינם.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "palanga-pier",
    "region": "palanga",
    "kind": "nature",
    "name": "Palanga Pier",
    "type": "Wooden pier",
    "typeHe": "רציף עץ",
    "rating": 4.7,
    "reviews": 5400,
    "price": null,
    "emoji": "🌅",
    "niv": "470 meters of wooden planks reaching into the Baltic. The sunsets here are the stuff of local legend.",
    "nivHe": "470 מטר של עץ לתוך הים הבלטי. השקיעות כאן הן אגדה מקומית.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "palanga-beach",
    "region": "palanga",
    "kind": "nature",
    "name": "Palanga Beach",
    "type": "Baltic beach",
    "typeHe": "חוף ים בלטי",
    "rating": 4.8,
    "reviews": 3200,
    "price": null,
    "emoji": "🏖️",
    "niv": "Wide, clean Baltic sand backed by pine dunes — the classic Lithuanian summer.",
    "nivHe": "חוף חול בלטי רחב ונקי עם דיונות אורן — הקיץ הליטאי הקלאסי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "brew-palanga",
    "region": "palanga",
    "kind": "cafe",
    "name": "BREW. Specialty Coffee",
    "type": "Specialty coffee",
    "typeHe": "קפה ספשלטי",
    "rating": 4.7,
    "reviews": 480,
    "price": "€5–12",
    "emoji": "☕",
    "niv": "The same excellent Vilnius roaster — now with a Bali-inspired terrace steps from the Baltic.",
    "nivHe": "אותה קלייה מצוינת מווילנה — עכשיו עם טרסה בהשראת באלי צעדים מהים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "fotokava-palanga",
    "region": "palanga",
    "kind": "cafe",
    "name": "Fotokava",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.6,
    "reviews": 320,
    "price": "€5–10",
    "emoji": "📷",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "cafe-banduke",
    "region": "palanga",
    "kind": "restaurant",
    "name": "Cafe Banduke",
    "type": "Restaurant",
    "typeHe": "מסעדה",
    "rating": 4.5,
    "reviews": 580,
    "price": "€15–30",
    "emoji": "🍽️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "basanaviciaus-street",
    "region": "palanga",
    "kind": "market",
    "name": "J. Basanavičiaus Street",
    "type": "Pedestrian promenade",
    "typeHe": "רחוב הולכי רגל",
    "rating": 4.5,
    "reviews": 1240,
    "price": null,
    "emoji": "🛍️",
    "niv": "The beating heart of Palanga — bars, restaurants, amber shops and street performers. Best at golden hour.",
    "nivHe": "לב פלאנגה הפועם — ברים, מסעדות, חנויות ענבר ורוקדי רחוב. הכי טוב בשקיעה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "caffeine-palanga",
    "region": "palanga",
    "kind": "cafe",
    "name": "Caffeine",
    "type": "Coffee shop",
    "typeHe": "בית קפה",
    "rating": 4.5,
    "reviews": 230,
    "price": "€5–10",
    "emoji": "☕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "senas-zvejas",
    "region": "curonian",
    "kind": "restaurant",
    "name": "Senas Žvejas",
    "type": "Fisherman's tavern",
    "typeHe": "פונדק דייגים",
    "rating": 4.6,
    "reviews": 380,
    "price": "€10–20",
    "emoji": "🎣",
    "niv": "Old fisherman's tavern with cepelinai and smoked fish — as authentic as Nida gets.",
    "nivHe": "פונדק דייגים ישן עם צפלינאי ודגים מעושנים — האותנטיות של נידה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "toda-nida",
    "region": "curonian",
    "kind": "restaurant",
    "name": "Todá",
    "type": "Middle Eastern",
    "typeHe": "מזרח תיכוני",
    "rating": 4.6,
    "reviews": 520,
    "price": "€15–25",
    "emoji": "🧆",
    "niv": "Israeli-Mediterranean on the Curonian Spit — hummus, mezze, and chargrilled meats between the dunes.",
    "nivHe": "ישראלי-ים תיכוני על רכס קורון — חומוס, מזה ובשרים על גחלים בין הדיונות.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "gitanos-blynai",
    "region": "curonian",
    "kind": "cafe",
    "name": "Gitanos Blynai",
    "type": "Crêpe café",
    "typeHe": "קפה קרפים",
    "rating": 4.7,
    "reviews": 290,
    "price": "€5–12",
    "emoji": "🥞",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "witches-hill",
    "region": "curonian",
    "kind": "culture",
    "name": "Witches' Hill (Juodkrantė)",
    "type": "Sculpture park",
    "typeHe": "פארק פסלים",
    "rating": 4.8,
    "reviews": 2800,
    "price": null,
    "emoji": "🧙",
    "niv": "80 ancient Lithuanian mythological wooden sculptures along a forest trail — haunting, beautiful, and free.",
    "nivHe": "80 פסלי עץ של מיתולוגיה ליטאית לאורך שביל יער — מרהיב, מקסים וחינם.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "thomas-mann-house-nida",
    "region": "curonian",
    "kind": "culture",
    "name": "Thomas Mann House",
    "type": "Literary museum",
    "typeHe": "מוזיאון ספרות",
    "rating": 4.5,
    "reviews": 680,
    "price": null,
    "emoji": "📚",
    "niv": "Where Thomas Mann spent three summers in the 1930s — a tiny wooden cottage full of light and literary history.",
    "nivHe": "כאן שהה תומאס מאן שלושה קיצות בשנות ה-30 — צריף עץ קטן מלא אור והיסטוריה ספרותית.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "nida-harbour",
    "region": "curonian",
    "kind": "nature",
    "name": "Nida Harbour",
    "type": "Lagoon harbour",
    "typeHe": "נמל הלגונה",
    "rating": 4.6,
    "reviews": 1150,
    "price": null,
    "emoji": "⛵",
    "niv": "Colourful fishing boats on the Curonian Lagoon — morning smoked-fish stalls, sailing dinghies, and pink sunrises.",
    "nivHe": "סירות דייגים צבעוניות על לגונת קורון — דוכני דגים בבוקר, מפרשיות וזריחות ורודות.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "stebuklai-spa",
    "region": "curonian",
    "kind": "stay",
    "name": "Stebuklai SPA",
    "type": "Luxury spa",
    "typeHe": "ספא יוקרתי",
    "rating": 4.9,
    "reviews": 210,
    "price": "€€€",
    "emoji": "🌊",
    "niv": "A rare luxury spa right in Nida — lagoon views, outdoor pools, and deep pine-forest silence. One of Lithuania's best.",
    "nivHe": "ספא יוקרתי נדיר בלב נידה — נוף ללגון, בריכות חיצוניות ושקט של יערות אורן. אחד הטובים בליטא.",
    "mapUrl": "https://maps.app.goo.gl/YxSPBL7PyRV1dwdV9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "monai-klaipeda",
    "region": "klaipeda",
    "kind": "restaurant",
    "name": "monai",
    "type": "Fine dining",
    "typeHe": "מסעדה יוקרתית",
    "rating": 4.6,
    "reviews": 920,
    "price": "€50+",
    "emoji": "⭐",
    "niv": "Michelin-recommended since 2022 — intimate, ingredient-driven tasting menu. Klaipėda's best table.",
    "nivHe": "מומלץ מישלן מ-2022 — תפריט טעימות אינטימי ומבוסס-חומרי-גלם. השולחן הטוב ביותר בקלייפדה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "ateik-ateik",
    "region": "klaipeda",
    "kind": "cafe",
    "name": "Ateik Ateik",
    "type": "Beach bar café",
    "typeHe": "בר חוף",
    "rating": 4.3,
    "reviews": 480,
    "price": "€5–15",
    "emoji": "🎸",
    "niv": "Watch ships leave the port over jazz and coffee at sunset. The most Klaipėda thing you can do.",
    "nivHe": "מסתכלים על ספינות יוצאות מהנמל עם ג'אז, קפה ושקיעה. הכי קלייפדה שיש.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "klaipeda-castle-museum",
    "region": "klaipeda",
    "kind": "culture",
    "name": "Klaipėda Castle Museum",
    "type": "History museum",
    "typeHe": "מוזיאון ההיסטוריה",
    "rating": 4.4,
    "reviews": 870,
    "price": null,
    "emoji": "🏰",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "klaipeda-old-town-walk",
    "region": "klaipeda",
    "kind": "culture",
    "name": "Klaipėda Old Town",
    "type": "Half-timbered old town",
    "typeHe": "עיר עתיקה",
    "rating": 4.5,
    "reviews": 2100,
    "price": null,
    "emoji": "🏘️",
    "niv": "German-Prussian half-timbered architecture, cobblestones, and the famous bronze Taravos Anikė sculpture.",
    "nivHe": "ארכיטקטורה גרמנית-פרוסית, אבני ריצוף ופסל ברונזה מפורסם — שווה ללכת בשקיעה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "clock-museum-klaipeda",
    "region": "klaipeda",
    "kind": "culture",
    "name": "Clock Museum",
    "type": "Specialty museum",
    "typeHe": "מוזיאון שעונים",
    "rating": 4.6,
    "reviews": 1240,
    "price": null,
    "emoji": "🕰️",
    "niv": "A surprisingly captivating collection of timepieces spanning 3,000 years — the sundials alone are worth it.",
    "nivHe": "אוסף מרתק באופן מפתיע של שעונים על פני 3,000 שנה — שעוני השמש לבדם שווים ביקור.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "toli-toli-druskininkai",
    "region": "druskininkai",
    "kind": "restaurant",
    "name": "Toli Toli",
    "type": "Fusion restaurant",
    "typeHe": "מסעדת פיוז'ן",
    "rating": 4.5,
    "reviews": 3990,
    "price": "€15–30",
    "emoji": "🍜",
    "niv": "Lithuanian-Asian fusion done right — nearly 4,000 reviews, creative dishes, and always packed.",
    "nivHe": "פיוז'ן ליטאי-אסיאתי מוצלח — כמעט 4,000 ביקורות, מנות יצירתיות ותמיד מלא.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "boulangerie-druskininkai",
    "region": "druskininkai",
    "kind": "cafe",
    "name": "Boulangerie Druskininkai",
    "type": "French bakery & café",
    "typeHe": "מאפייה צרפתית",
    "rating": 4.6,
    "reviews": 1894,
    "price": "€5–10",
    "emoji": "🥐",
    "niv": "A little piece of Paris in the middle of Druskininkai — flaky, buttery croissants, beautiful pastries and smooth coffee. The perfect morning stop before a spa day.",
    "nivHe": "פינת פריז קטנה בלב דרוסקיניינקאי — קרואסונים חמאתיים ופריכים, מאפים יפהפיים וקפה מצוין. עצירת בוקר מושלמת לפני יום ספא.",
    "mapUrl": "https://maps.app.goo.gl/rwHinzG78ThpsNME9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "sicilia-druskininkai",
    "region": "druskininkai",
    "kind": "restaurant",
    "name": "Sicilia",
    "type": "Italian restaurant",
    "typeHe": "מסעדה איטלקית",
    "rating": 4.3,
    "reviews": 1056,
    "price": "€8–18",
    "emoji": "🍕",
    "niv": "A proper Italian restaurant with seriously good food — one of the best dining options in Druskininkai.",
    "nivHe": "מסעדה איטלקית אמיתית ברמה גבוהה עם אוכל נהדר — אחת מאפשרויות האוכל הטובות ביותר בדרוסקיניינקאי.",
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "druskininkai-aqua-park",
    "region": "druskininkai",
    "kind": "nature",
    "name": "Druskininkai Aqua Park",
    "type": "Water park & spa",
    "typeHe": "פארק מים",
    "rating": 4.4,
    "reviews": 3800,
    "price": null,
    "emoji": "🏊",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "dzukija-national-park",
    "region": "druskininkai",
    "kind": "nature",
    "name": "Dzūkija National Park",
    "type": "National park",
    "typeHe": "פארק לאומי",
    "rating": 4.8,
    "reviews": 1850,
    "price": null,
    "emoji": "🌲",
    "niv": "Lithuania's largest national park — ancient mushroom-picking forests, sandy rivers, and village beekeepers.",
    "nivHe": "הפארק הלאומי הגדול ביותר בליטא — יערות קטיף פטריות עתיקים, נהרות חוליים ודבוראים כפריים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "city-coffee-druskininkai",
    "region": "druskininkai",
    "kind": "cafe",
    "name": "City Coffee",
    "type": "Espresso bar",
    "typeHe": "בר אספרסו",
    "rating": 4.8,
    "reviews": 853,
    "price": "€1–5",
    "emoji": "☕",
    "niv": "The best coffee in Druskininkai — a tiny, cozy espresso bar with outstanding flat whites. I really enjoyed the coffee and the service. Highly recommend.",
    "nivHe": "הקפה הכי טוב בדרוסקינינקאי — בר אספרסו קטן ונעים עם פלאט-וויט מעולה. נהניתי מהקפה ומהשירות. ממליץ בחום.",
    "mapUrl": "https://maps.app.goo.gl/79Hm8ACTXc4Mauyb8",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "snow-arena-druskininkai",
    "region": "druskininkai",
    "kind": "nature",
    "name": "Snow Arena Druskininkai",
    "type": "Indoor ski resort",
    "typeHe": "אתר סקי מקורה",
    "rating": 4.4,
    "reviews": 6681,
    "price": null,
    "emoji": "⛷️",
    "niv": "A covered ski complex open all year round — great for beginners and also has a professional section. Excellent service, unique experience especially in summer. One of a kind in the Baltics.",
    "nivHe": "קומפלקס סקי מקורה הפועל כל השנה — מצוין למתחילים ויש גם חלק מקצועי. שירות מעולה, חוויה ייחודית במיוחד בקיץ. אחד מסוגו בבלטיים.",
    "mapUrl": "https://maps.app.goo.gl/f1zAosWs9947cp1w9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "vijunele-park",
    "region": "druskininkai",
    "kind": "nature",
    "name": "Vijūnėlė Park",
    "type": "Lakeside park",
    "typeHe": "פארק על האגם",
    "rating": 4.8,
    "reviews": 3007,
    "price": null,
    "emoji": "🦢",
    "niv": "A beautiful lakeside park with a beach, electric scooter and boat rentals, outdoor gym, and basketball courts. Perfect for a relaxed afternoon stroll or an active day out in Druskininkai.",
    "nivHe": "פארק יפהפה על האגם עם חוף, השכרת קורקינטים חשמליים וסירות, חדר כושר פתוח ומגרשי כדורסל. מושלם לטיול אחר הצהריים נינוח או יום פעיל בדרוסקינינקאי.",
    "mapUrl": "https://maps.app.goo.gl/zBu5eJcbodEyTJBa9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "uno-park-druskininkai",
    "region": "druskininkai",
    "kind": "nature",
    "name": "UNO Park Druskininkai",
    "type": "Adventure rope park",
    "typeHe": "פארק הרפתקאות",
    "rating": 4.9,
    "reviews": 884,
    "price": null,
    "emoji": "🌲",
    "niv": "An amazing adventure rope park in the middle of a pine forest — tracks for all ages and skill levels, including a zip line over the Nemunas river. A must for anyone visiting with kids or seeking an adrenaline kick.",
    "nivHe": "פארק הרפתקאות מדהים בתוך יער אורנים — מסלולים לכל הגילאים ורמות הכישרון, כולל זיפ-ליין מעל נהר נמונס. חובה לכל מי שמגיע עם ילדים או מחפש אדרנלין.",
    "mapUrl": "https://maps.app.goo.gl/AxUNLqP6g6o6ZQVS9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "spa-vilnius-druskininkai",
    "region": "druskininkai",
    "kind": "stay",
    "name": "SPA VILNIUS Druskininkai",
    "type": "4-star spa hotel",
    "typeHe": "מלון ספא 4 כוכבים",
    "rating": 4.7,
    "reviews": 2092,
    "price": null,
    "emoji": "💆",
    "niv": "The best spa hotel in Druskininkai — top-quality treatments, super professional staff, and an extraordinary relaxation experience. I've been coming back here for years. Highest recommendation.",
    "nivHe": "מלון הספא הכי טוב בדרוסקינינקאי — טיפולים ברמה הגבוהה ביותר, צוות מקצועי מאוד וחוויית רגיעה יוצאת דופן. אני חוזר לכאן כבר שנים. המלצה הכי גבוהה שיש.",
    "mapUrl": "https://maps.app.goo.gl/7cU9qgF2ncs7Z6WH6",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "druskininkai-tourism-center",
    "region": "druskininkai",
    "kind": "culture",
    "name": "Druskininkai Tourism & Business Info Center",
    "type": "Tourist information center",
    "typeHe": "מרכז מידע תיירותי",
    "rating": 4.5,
    "reviews": 107,
    "price": null,
    "emoji": "ℹ️",
    "niv": "The best first stop in Druskininkai — the staff will help you plan your day, recommend the best spots, and answer any question about the city. Friendly, helpful, and speak great English.",
    "nivHe": "העצירה הראשונה הכי טובה בדרוסקינינקאי — הצוות יעזור לכם לתכנן את היום, ימליץ על המקומות הכי שווים ויענה על כל שאלה על העיר. ידידותיים, מועילים ומדברים אנגלית מצוינת.",
    "mapUrl": "https://maps.app.goo.gl/69Q1uGcNPYEMFhYp6",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "moletai-observatory",
    "region": "moletai",
    "kind": "culture",
    "name": "Molėtai Astronomical Observatory",
    "type": "Observatory",
    "typeHe": "מצפה כוכבים",
    "rating": 4.7,
    "reviews": 1250,
    "price": null,
    "emoji": "🔭",
    "niv": "The largest scientific telescope in Northern Europe — public stargazing nights are magical. Book ahead.",
    "nivHe": "הטלסקופ המדעי הגדול ביותר בצפון אירופה — ערבי תצפית לציבור קסומים. להזמין מראש.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "ethnocosmology-museum",
    "region": "moletai",
    "kind": "culture",
    "name": "Museum of Ethnocosmology",
    "type": "Museum",
    "typeHe": "מוזיאון",
    "rating": 4.6,
    "reviews": 480,
    "price": null,
    "emoji": "🌌",
    "niv": "Where Lithuanian cosmic mythology meets real science — shaped like the mythological World Tree.",
    "nivHe": "כאן מיתולוגיה קוסמית ליטאית פוגשת מדע אמיתי — בצורת עץ העולם המיתולוגי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "labanoras-observation-tower",
    "region": "moletai",
    "kind": "nature",
    "name": "Labanoras Observation Tower",
    "type": "Viewpoint",
    "typeHe": "מגדל תצפית",
    "rating": 4.6,
    "reviews": 390,
    "price": null,
    "emoji": "🗼",
    "niv": "Lithuania's second-tallest tower — 214 steps and a panorama over the Lakajai lakes and endless pine forest.",
    "nivHe": "המגדל השני בגובהו בליטא — 214 מדרגות ופנורמה על אגמי לאקאיי ויער אורן אינסופי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "dubingiai-stud-farm",
    "region": "moletai",
    "kind": "restaurant",
    "name": "Dubingiai Stud Farm",
    "type": "Farm restaurant",
    "typeHe": "מסעדת חווה",
    "rating": 4.5,
    "reviews": 215,
    "price": "€20–40",
    "emoji": "🐴",
    "niv": "Dine overlooking the paddocks and a lake on a working horse stud farm — genuinely unique.",
    "nivHe": "ארוחה עם נוף לאורוות ואגם בחוות סוסים פעילה — חוויה ייחודית לגמרי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "moletai-lake-district",
    "region": "moletai",
    "kind": "nature",
    "name": "Molėtai Lake District",
    "type": "Lake landscape",
    "typeHe": "אזור אגמים",
    "rating": 4.8,
    "reviews": 560,
    "price": null,
    "emoji": "💙",
    "niv": "Over 300 lakes within the district — canoe routes, fishing, and lakeside saunas. Dark-sky reserve at night.",
    "nivHe": "מעל 300 אגמים במחוז — מסלולי קאנו, דיג וסאונות על האגם. שמיים חשוכים בלילה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "moletai-sculpture-park",
    "region": "moletai",
    "kind": "culture",
    "name": "Molėtai Sculpture Park",
    "type": "Outdoor sculpture park",
    "typeHe": "פארק פסלים",
    "rating": 4.4,
    "reviews": 145,
    "price": null,
    "emoji": "🗿",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "aukstaitija-national-park",
    "region": "countryside",
    "kind": "nature",
    "name": "Aukštaitija National Park",
    "type": "National park",
    "typeHe": "פארק לאומי",
    "rating": 4.8,
    "reviews": 4500,
    "price": null,
    "emoji": "🏞️",
    "niv": "200+ lakes, old-growth forest and canoe routes that feel like another century. Lithuania's most beautiful park.",
    "nivHe": "200+ אגמים, יערות עתיקים ומסלולי קאנו שמרגישים כמו מאה אחרת. הפארק היפה ביותר בליטא.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "beekeeping-museum-stripeikiai",
    "region": "countryside",
    "kind": "culture",
    "name": "Ancient Beekeeping Museum",
    "type": "Open-air museum",
    "typeHe": "מוזיאון פתוח-אוויר",
    "rating": 4.7,
    "reviews": 1650,
    "price": null,
    "emoji": "🐝",
    "niv": "Ancient log beehives, forest sculptures, and honey tasting. A uniquely Lithuanian experience.",
    "nivHe": "כוורות בול עץ עתיקות, פסלי יער וטעימת דבש. חוויה ייחודית לליטא.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "paluse-wooden-church",
    "region": "countryside",
    "kind": "culture",
    "name": "Palūšė Wooden Church",
    "type": "Historic church",
    "typeHe": "כנסייה היסטורית",
    "rating": 4.7,
    "reviews": 810,
    "price": null,
    "emoji": "⛪",
    "niv": "A 1750 wooden church reflected in the lake — the most iconic image in Aukštaitija National Park.",
    "nivHe": "כנסיית עץ מ-1750 המשתקפת באגם — הדימוי המזוהה ביותר עם הפארק הלאומי.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "vila-gervalis",
    "region": "countryside",
    "kind": "stay",
    "name": "Vila Gervalis",
    "type": "Lakeside hotel & spa",
    "typeHe": "מלון וספא על האגם",
    "rating": 4.6,
    "reviews": 640,
    "price": null,
    "emoji": "🌅",
    "niv": "Lakeside spa retreat — the most comfortable base for exploring the Aukštaitija lakes.",
    "nivHe": "נסיגה לאגם עם ספא — הבסיס הנוח ביותר לגילוי אגמי אוקשטאיטיה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "ginuciai-hill-fort",
    "region": "countryside",
    "kind": "nature",
    "name": "Ginučiai Hill Fort",
    "type": "Archaeological viewpoint",
    "typeHe": "גבעת מבצר",
    "rating": 4.6,
    "reviews": 420,
    "price": null,
    "emoji": "⛰️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kretinga-manor-winter-garden",
    "region": "palanga",
    "kind": "culture",
    "name": "Kretinga Manor & Winter Garden",
    "type": "Museum & conservatory",
    "typeHe": "מוזיאון וגן חורפי",
    "rating": 4.6,
    "reviews": 1850,
    "price": null,
    "emoji": "🌿",
    "niv": "5,000 tropical plants in a 19th-century glass conservatory — with live parrots, turtles, and banana trees.",
    "nivHe": "5,000 צמחים טרופיים בחממת זכוכית מהמאה ה-19 — עם תוכים חיים, צבים ועצי בננה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "franciscan-monastery-kretinga",
    "region": "palanga",
    "kind": "culture",
    "name": "Franciscan Monastery & Church",
    "type": "Historic monastery",
    "typeHe": "מנזר היסטורי",
    "rating": 4.5,
    "reviews": 610,
    "price": null,
    "emoji": "⛪",
    "niv": "A working 17th-century Franciscan monastery at the centre of town — austere, beautiful, very peaceful.",
    "nivHe": "מנזר פרנציסקני פעיל מהמאה ה-17 במרכז העיר — מאופק, יפה ושקט מאוד.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "cafe-old-palace-kretinga",
    "region": "palanga",
    "kind": "cafe",
    "name": "Café Inside Old Palace",
    "type": "Café in manor",
    "typeHe": "קפה בארמון",
    "rating": 4.4,
    "reviews": 285,
    "price": "€5–12",
    "emoji": "🫖",
    "niv": "Coffee surrounded by exotic plants and turtles inside the Kretinga Manor conservatory. Genuinely magical.",
    "nivHe": "קפה בין צמחים טרופיים וצבים בחממת ארמון קרטינגה. קסום באמת.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "cable-park-313",
    "region": "palanga",
    "kind": "nature",
    "name": "313 Cable Park",
    "type": "Wakeboard park",
    "typeHe": "פארק גלישת כבלים",
    "rating": 4.6,
    "reviews": 520,
    "price": null,
    "emoji": "🏄",
    "niv": "One of Europe's most advanced cable wakeboard parks — fun for first-timers, serious for pros.",
    "nivHe": "אחד מפארקי הוויקבורד בכבלים המתקדמים באירופה — כיפי למתחילים ורציני לקשוחים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "lourdes-grotto-kretinga",
    "region": "palanga",
    "kind": "culture",
    "name": "Lourdes Grotto",
    "type": "Religious landmark",
    "typeHe": "אתר דתי",
    "rating": 4.5,
    "reviews": 430,
    "price": null,
    "emoji": "🙏",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kretinga-park",
    "region": "palanga",
    "kind": "nature",
    "name": "Kretinga Manor Park",
    "type": "Manor park",
    "typeHe": "פארק האחוזה",
    "rating": 4.5,
    "reviews": 720,
    "price": null,
    "emoji": "🌳",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "kretinga-museum",
    "region": "palanga",
    "kind": "culture",
    "name": "Kretinga Museum",
    "type": "Regional museum",
    "typeHe": "מוזיאון אזורי",
    "rating": 4.4,
    "reviews": 380,
    "price": null,
    "emoji": "🏛️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "ai"
  },
  {
    "id": "pajurio-parkas",
    "region": "palanga",
    "kind": "nature",
    "name": "Pajūrio Regional Park",
    "type": "Coastal nature park",
    "typeHe": "פארק חוף טבעי",
    "rating": 4.7,
    "reviews": 480,
    "price": null,
    "emoji": "🌾",
    "niv": "Dunes, lagoons, and migratory bird routes along the coast between Kretinga and the sea.",
    "nivHe": "דיונות, לגונות ומסלולי ציפורים נודדות לאורך החוף בין קרטינגה לים.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "kernave-archaeological",
    "region": "countryside",
    "kind": "culture",
    "name": "Kernavė Archaeological Site",
    "type": "UNESCO heritage site",
    "typeHe": "אתר מורשת עולמית",
    "rating": 4.7,
    "reviews": 2100,
    "price": null,
    "emoji": "⛰️",
    "niv": "Lithuania's oldest capital — five dramatic hill forts on the Neris river. UNESCO-listed, almost no crowds.",
    "nivHe": "הבירה הקדומה ביותר של ליטא — חמש גבעות מבצר על נהר נריס. אתר UNESCO, כמעט ללא המון.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-island-castle",
    "region": "trakai",
    "kind": "culture",
    "name": "Trakai Island Castle",
    "type": "Medieval castle",
    "typeHe": "טירה מימי ביניים",
    "rating": 4.7,
    "reviews": 18500,
    "price": null,
    "emoji": "🏰",
    "niv": "A 14th-century red-brick castle rising from a lake — Lithuania's most iconic image. Rent a rowboat and circle it.",
    "nivHe": "טירה מהמאה ה-14 עולה מתוך אגם — הדימוי הכי אייקוני של ליטא. שכר סירת חתירה וחתור סביבה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "s-shapshal-karaim-museum",
    "region": "trakai",
    "kind": "culture",
    "name": "S. Shapshal Karaite Ethnographic Museum",
    "type": "Ethnographic museum",
    "typeHe": "מוזיאון אתנוגרפי",
    "rating": 4.0,
    "reviews": 57,
    "price": "€1–3",
    "emoji": "🏛️",
    "niv": "Europe's only museum dedicated to the Karaim people — a small Turkic, Old Testament-following community that Grand Duke Vytautas brought from Crimea to Trakai 600 years ago. Three modest rooms hold 300+ artifacts: traditional dress, Eastern weapons, an antique wooden cradle, ceremonial coffee pots. A quick, fascinating stop on the way between the two castles, steps from the still-active Karaim kenesa (prayer house).",
    "nivHe": "המוזיאון היחיד באירופה המוקדש לעם הקראי — קהילה טורקית קטנה ההולכת לפי התנ\"ך בלי פרשנות מאוחרת, שהדוכס ויטאוטס הביא מקרים לטראקאי לפני 600 שנה. בשלושה חללים קטנים יותר מ-300 מוצגים: בגדים מסורתיים, נשק מזרחי, עריסת תינוקות עתיקה וקנקני קפה טקסיים. עצירה קצרה ומרתקת בדרך בין שתי הטירות, כמה צעדים מהקנסה הקראית שעדיין פעילה.",
    "mapUrl": "https://maps.app.goo.gl/dEFMTZ6tC54iy1ma6",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "esperanza-lake-resort-spa",
    "region": "trakai",
    "kind": "stay",
    "name": "Esperanza Lake Resort & Spa",
    "type": "Lakeside design hotel & spa",
    "typeHe": "מלון בוטיק וספא על האגם",
    "rating": 4.8,
    "reviews": 148,
    "price": null,
    "emoji": "💆",
    "niv": "Eleven hectares of private forest on the shore of Lake Ungurys, ten minutes from Trakai's castles — built from century-old Canadian cedar in a calm, minimalist style. Days drift between the lake, the woods (where two resident alpacas roam), and Spa Esperanza's pool, sauna, hammam and salt room. A place built for doing absolutely nothing, beautifully.",
    "nivHe": "אחת עשרה הקטרים של יער פרטי על שפת אגם אונגוריס, עשר דקות נסיעה מהטירות של טראקאי — בנוי מעץ ארז קנדי עתיק, בסטייל מינימליסטי ורגוע. הימים מתמזגים בין האגם, היער (ששם גרים שני אלפקות) וספא אספרנזה עם בריכה, סאונה, חמאם וחדר מלח. מקום שנבנה בשביל לא לעשות כלום, ברמה הכי יפה שיש.",
    "mapUrl": "https://www.google.com/maps/place/Esperanza+Resort+%26+SPA/@54.616408,24.8080203,11.75z/data=!4m9!3m8!1s0x46ddf6422bda2049:0x5bd6cb0973f7a15b!5m2!4m1!1i2!8m2!3d54.6048228!4d24.7470474!16s%2Fg%2F1pp2vc_fn?entry=ttu&g_ep=EgoyMDI2MDYyMi4wIKXMDSoASAFQAw%3D%3D",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "anyksciai-treetop-path",
    "region": "countryside",
    "kind": "nature",
    "name": "Anykščiai Treetop Path",
    "type": "Forest walkway",
    "typeHe": "שביל יער על ראשי עצים",
    "rating": 4.6,
    "reviews": 3200,
    "price": null,
    "emoji": "🌳",
    "niv": "A 300-metre elevated walkway through the forest canopy — the views, sounds, and silence are extraordinary.",
    "nivHe": "שביל מוגבה של 300 מטר בחופת היער — הנופים, הצלילים והשקט יוצאי דופן.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "kibinai-senoji",
    "region": "trakai",
    "kind": "restaurant",
    "name": "Senoji Kibininė",
    "type": "Traditional Karaim kitchen",
    "typeHe": "מטבח קראימי מסורתי",
    "rating": 4.5,
    "reviews": 2800,
    "price": "€5–15",
    "emoji": "🥐",
    "niv": "The best kibinai (Karaim meat pies) in Lithuania — baked fresh in Trakai from a 600-year-old recipe.",
    "nivHe": "הקיביני הכי טובים בליטא — נאפים טריים בטראקאי ממתכון בן 600 שנה.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "le-vivier-trakai",
    "region": "trakai",
    "kind": "restaurant",
    "name": "Le Vivier Trakai",
    "type": "European restaurant",
    "typeHe": "מסעדה אירופאית",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🍽️",
    "niv": "A refined European restaurant on the lake — one of Trakai's more upscale dining options.",
    "nivHe": "מסעדה אירופאית משובחת על האגם — אחת מהאפשרויות הייצוגיות לאכול בטראקאי.",
    "mapUrl": "https://maps.app.goo.gl/We4C8GY3AKT7nX3eA",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "aj-sokoladas",
    "region": "trakai",
    "kind": "cafe",
    "name": "AJ Šokoladas",
    "type": "Chocolate & coffee shop",
    "typeHe": "בית קפה שוקולד",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🍫",
    "niv": "A sweet stop for handmade chocolates and specialty coffee in Trakai's town center.",
    "nivHe": "עצירה מתוקה לשוקולדים עשויים ביד וקפה איכותי במרכז העיירה.",
    "mapUrl": "https://maps.app.goo.gl/JdY3tPMLLihB1WwH9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-balloon-ride",
    "region": "trakai",
    "kind": "nature",
    "name": "Balloon Ride Trakai",
    "type": "Hot air balloon tour",
    "typeHe": "טיסת בלון",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🎈",
    "niv": "Float over Trakai's lakes and medieval castle in a hot air balloon — one of the most memorable views in Lithuania.",
    "nivHe": "להמריא מעל אגמי טראקאי והטירה המימי-ביניימית בבלון פורח — אחד הנופים הבלתי נשכחים ביותר בליטא.",
    "mapUrl": "https://maps.app.goo.gl/vHtHg7oFGszWrftt9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-tourist-info",
    "region": "trakai",
    "kind": "culture",
    "name": "Trakai Tourist Information Center",
    "type": "Tourist information",
    "typeHe": "מרכז מידע לתייר",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "ℹ️",
    "niv": "The official starting point for any visit to Trakai — maps, event listings, and local recommendations.",
    "nivHe": "נקודת הפתיחה הרשמית לכל ביקור בטראקאי — מפות, אירועים, והמלצות מקומיות.",
    "mapUrl": "https://maps.app.goo.gl/mefhfCwMv6oX8wtU7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-boat-rental",
    "region": "trakai",
    "kind": "nature",
    "name": "Boat Rental Trakai",
    "type": "Rowboat & paddleboat rental",
    "typeHe": "השכרת סירות",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "⛵",
    "niv": "Rent a rowboat or pedalo on Lake Galvė and paddle up to the island castle — one of Trakai's most iconic experiences.",
    "nivHe": "שכרו סירה על אגם גלווה וחתרו עד לטירת האי — אחת החוויות הכי אייקוניות בטראקאי.",
    "mapUrl": "https://maps.app.goo.gl/N59Aboj2uDnVZYx97",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-history-museum",
    "region": "trakai",
    "kind": "culture",
    "name": "Trakai History Museum",
    "type": "History museum",
    "typeHe": "מוזיאון ההיסטוריה של טראקאי",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🏛️",
    "niv": "Housed inside Trakai Island Castle, the museum tells the story of the Grand Duchy of Lithuania through artifacts, weapons, and medieval exhibits.",
    "nivHe": "מאוכסן בתוך טירת האי, המוזיאון מספר את סיפור הדוכסות הגדולה של ליטא דרך חפצים, נשק ותצוגות מימי הביניים.",
    "mapUrl": "https://maps.app.goo.gl/NTbPVQsz7W61AS9X8",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "kiubete-trakai",
    "region": "trakai",
    "kind": "restaurant",
    "name": "Kiubėtė",
    "type": "Lithuanian restaurant",
    "typeHe": "מסעדה ליטאית",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🍽️",
    "niv": "A well-regarded restaurant in Trakai serving traditional Lithuanian dishes with a scenic lakeside setting.",
    "nivHe": "מסעדה מוערכת בטראקאי המגישה מנות ליטאיות מסורתיות עם נוף לאגם.",
    "mapUrl": "https://maps.app.goo.gl/NafX4WiecRcK7x5q8",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "trakai-beach",
    "region": "trakai",
    "kind": "nature",
    "name": "Trakai Beach",
    "type": "Lake beach",
    "typeHe": "חוף אגם",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🏖️",
    "niv": "A sandy lake beach on the shores of Trakai — perfect for a summer swim after exploring the castle.",
    "nivHe": "חוף אגם חולי על שפת טראקאי — מושלם לשחייה קיצית אחרי ביקור בטירה.",
    "mapUrl": "https://maps.app.goo.gl/YvT8bEsEMt4YXzkb7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "varnikai-nature-trail",
    "region": "trakai",
    "kind": "nature",
    "name": "Varnikai Nature Trail",
    "type": "Nature trail",
    "typeHe": "שביל טבע",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🌿",
    "niv": "A quiet nature trail through the forests and lakeside landscapes around Trakai — ideal for a slow walk between sights.",
    "nivHe": "שביל טבע שקט דרך היערות ונופי האגם סביב טראקאי — אידיאלי לטיול רגוע בין האתרים.",
    "mapUrl": "https://maps.app.goo.gl/goWB8W8ZPRLHiana7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "maisto-oaze-terasa",
    "region": "trakai",
    "kind": "restaurant",
    "name": "Maisto oazė Terasa",
    "type": "Terrace restaurant",
    "typeHe": "מסעדת טרסה",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🍽️",
    "niv": "An outdoor terrace restaurant with relaxed lakeside vibes — a good spot to sit and eat in Trakai.",
    "nivHe": "מסעדת טרסה פתוחה עם אווירה רגועה ליד האגם — מקום טוב לשבת ולאכול בטראקאי.",
    "mapUrl": "https://maps.app.goo.gl/gzTdvqe8kQaMwdAa6",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "dzukija-pine-forests",
    "region": "countryside",
    "kind": "nature",
    "name": "Dzūkija Pine Forests",
    "type": "Forest & mushroom picking",
    "typeHe": "יערות וקטיף פטריות",
    "rating": 4.8,
    "reviews": 1200,
    "price": null,
    "emoji": "🍄",
    "niv": "In autumn the whole of southern Lithuania heads into these ancient forests to pick mushrooms. Join them.",
    "nivHe": "בסתיו כל דרום ליטא נכנס ליערות האלה לקטוף פטריות. הצטרפו.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "seduva-jewish-museum",
    "region": "countryside",
    "kind": "culture",
    "name": "Šeduva Jewish Museum",
    "type": "Jewish heritage museum",
    "typeHe": "מוזיאון מורשת יהודית",
    "rating": null,
    "reviews": null,
    "price": null,
    "emoji": "🕍",
    "niv": "One of the most profound and moving experiences in all of Lithuania. Hidden in the tiny town of Šeduva, this museum tells the story of a Jewish community that was almost entirely wiped out. Walking through it is deeply emotional — a reminder of what was, and what was lost. Do not skip this.",
    "nivHe": "אחת מהחוויות העמוקות והמרגשות ביותר בכל ליטא. חבוי בעיירה הקטנטנה שדובה, המוזיאון מספר את סיפורה של קהילה יהודית שנמחקה כמעט לחלוטין. לעבור דרכו זה מחריד ומרגש עד דמעות — תזכורת למה שהיה ולמה שאבד. אל תפספסו את זה.",
    "mapUrl": "https://maps.app.goo.gl/fDZaRGMxjNNMocgC9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "alantos-zirgai",
    "region": "countryside",
    "kind": "stay",
    "name": "Alantos Žirgai",
    "type": "Lakeside horse farm & holiday homes",
    "typeHe": "חווה עם סוסים ובתי נופש ליד האגם",
    "rating": 4.9,
    "reviews": 145,
    "price": null,
    "emoji": "🐎",
    "niv": "An incredible countryside escape near Alanta — two beautiful lakeside houses for rent on a working horse farm. The owners are some of the warmest hosts I've met in Lithuania: they invited me in for coffee, cooked a meal, and showed me the whole area. Pure Lithuanian countryside magic.",
    "nivHe": "בריחה כפרית מדהימה ליד אלנטה — שני בתי נופש ליד האגם על חווה עם סוסים. הבעלים הם מהמארחים החמים ביותר שפגשתי בליטא: הם הזמינו אותי לקפה, בישלו ארוחה ועשו לי סיור באזור. קסם כפרי ליטאי אמיתי.",
    "mapUrl": "https://maps.app.goo.gl/HqSeQMyKHdLB715D7",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "astriosios-kirsnos-dvaras",
    "region": "countryside",
    "kind": "stay",
    "name": "Aštriosios Kirsnos dvaras",
    "type": "Historic manor & estate stay",
    "typeHe": "אחוזה היסטורית ולינה",
    "rating": 4.6,
    "reviews": 265,
    "price": null,
    "emoji": "🏰",
    "niv": "A stunning historic manor estate in the quiet Suvalkija countryside, near the Lithuanian-Polish border. Beautiful old architecture, peaceful surroundings — the kind of place that feels frozen in time.",
    "nivHe": "אחוזה היסטורית מרהיבה באזור הכפרי השקט של סובלקיה, ליד הגבול הליטאי-פולני. ארכיטקטורה עתיקה יפיפייה וסביבה שלווה — מקום שמרגיש כאילו הזמן עמד בו מלכת.",
    "mapUrl": "https://maps.app.goo.gl/Qw6T6vro7RgFHTCV9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "genio-kampas-treehouse",
    "region": "countryside",
    "kind": "stay",
    "name": "Genio kampas Treehouse",
    "type": "Treehouse lodge with lake view",
    "typeHe": "בית עץ עם נוף לאגם",
    "rating": 4.9,
    "reviews": 24,
    "price": null,
    "emoji": "🌲",
    "niv": "One of Lithuania's most unique stays — a treehouse lodge deep in the forest with a spectacular lake view. Completely off-grid feeling, surrounded by nature. Perfect for a true digital detox.",
    "nivHe": "אחד מהמקומות הייחודיים ביותר לשהייה בליטא — בית עץ ביער עמוק עם נוף מרהיב לאגם. תחושה של ניתוק מוחלט מהעולם, מוקף בטבע. מושלם לדטוקס דיגיטלי אמיתי.",
    "mapUrl": "https://maps.app.goo.gl/5o6WXyaa4GJuanPZ9",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "uoksas-kaunas",
    "region": "kaunas",
    "kind": "restaurant",
    "name": "Uoksas",
    "type": "Farm-to-table bistro",
    "typeHe": "ביסטרו שדה-לשולחן",
    "rating": 4.7,
    "reviews": 890,
    "price": "€15–30",
    "emoji": "🍽️",
    "niv": "Kaunas's standout seasonal bistro — creative Lithuanian dishes and natural wine in a Bauhaus-era building.",
    "nivHe": "הביסטרו העונתי הבולט של קאונאס — מנות ליטאיות יצירתיות ויין טבעי בבניין בסגנון באוהאוס.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "ciurlionis-art-museum",
    "region": "kaunas",
    "kind": "culture",
    "name": "M. K. Čiurlionis Art Museum",
    "type": "Art museum",
    "typeHe": "מוזיאון אמנות",
    "rating": 4.7,
    "reviews": 2400,
    "price": null,
    "emoji": "🎨",
    "niv": "Lithuania's greatest art collection — including the haunting symbolist paintings of Čiurlionis himself.",
    "nivHe": "אוסף האמנות הגדול ביותר בליטא — כולל ציורי הסימבוליזם המרגשים של צ'ורליוניס עצמו.",
    "status": "approved",
    "source": "niv"
  },
  {
    "id": "kaunas-castle",
    "region": "kaunas",
    "kind": "culture",
    "name": "Kaunas Castle",
    "type": "Medieval castle",
    "typeHe": "טירה מימי הביניים",
    "rating": 4.6,
    "reviews": 8466,
    "price": null,
    "emoji": "🏰",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "azuolyno-parkas",
    "region": "kaunas",
    "kind": "nature",
    "name": "Ąžuolyno parkas",
    "type": "Park",
    "typeHe": "פארק",
    "rating": 4.7,
    "reviews": 6093,
    "price": null,
    "emoji": "🌳",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "bundu-kaunas",
    "region": "kaunas",
    "kind": "cafe",
    "name": "Bundu",
    "type": "Bakery",
    "typeHe": "מאפייה",
    "rating": 4.8,
    "reviews": 263,
    "price": "€5–10",
    "emoji": "🥐",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "meno-materija",
    "region": "kaunas",
    "kind": "cafe",
    "name": "Meno Materija SHOP & CAFÉ",
    "type": "Café & gift shop",
    "typeHe": "בית קפה וחנות מתנות",
    "rating": 5.0,
    "reviews": 40,
    "price": null,
    "emoji": "🎨",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "dia-kaunas",
    "region": "kaunas",
    "kind": "restaurant",
    "name": "DIA",
    "type": "Fine dining",
    "typeHe": "מסעדת שף",
    "rating": 4.8,
    "reviews": 1648,
    "price": "€50+",
    "emoji": "🍽️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "zalgirio-arena",
    "region": "kaunas",
    "kind": "culture",
    "name": "Žalgirio arena",
    "type": "Sports arena",
    "typeHe": "זירת ספורט",
    "rating": 4.7,
    "reviews": 23491,
    "price": null,
    "emoji": "🏀",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "numan-kaunas",
    "region": "kaunas",
    "kind": "restaurant",
    "name": "Nüman",
    "type": "Fine dining",
    "typeHe": "מסעדת שף",
    "rating": 4.7,
    "reviews": 588,
    "price": "€50+",
    "emoji": "🍽️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "neighbourhood-kaunas",
    "region": "kaunas",
    "kind": "restaurant",
    "name": "NEIGHBOURHOOD",
    "type": "Pizza restaurant",
    "typeHe": "פיצרייה",
    "rating": 4.9,
    "reviews": 237,
    "price": "€15–20",
    "emoji": "🍕",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "kaunas-tourism-info",
    "region": "kaunas",
    "kind": "info",
    "name": "Kaunas Tourism Information Centre",
    "type": "Tourist information",
    "typeHe": "מרכז מידע לתיירים",
    "rating": 4.4,
    "reviews": 131,
    "price": null,
    "emoji": "ℹ️",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "radisson-kaunas",
    "region": "kaunas",
    "kind": "hotel",
    "name": "Radisson Hotel Kaunas",
    "type": "4-star hotel",
    "typeHe": "מלון 4 כוכבים",
    "rating": 4.5,
    "reviews": 2785,
    "price": null,
    "emoji": "🏨",
    "niv": null,
    "nivHe": null,
    "status": "pending",
    "source": "niv"
  },
  {
    "id": "viesbutis-kaunas",
    "region": "kaunas",
    "kind": "hotel",
    "name": "Viešbutis KAUNAS",
    "type": "4-star hotel",
    "typeHe": "מלון 4 כוכבים",
    "rating": 4.5,
    "reviews": 2481,
    "price": null,
    "emoji": "🏨",
    "niv": null,
    "nivHe": null,
    "mapUrl": "https://maps.app.goo.gl/tZe6vhPkKECkdLV18",
    "status": "pending",
    "source": "niv"
  }
];

// Landmarks for the itinerary timeline (sights, not in Niv's list)
const LANDMARKS = [
  { id: 'gediminas', region: 'vilnius', he: { name: 'מגדל גדימינאס' }, en: { name: 'Gediminas Tower' } },
  { id: 'uzupis', region: 'vilnius', he: { name: 'רפובליקת אוז\'ופיס' }, en: { name: 'Užupis Republic' } },
  { id: 'cathedral', region: 'vilnius', he: { name: 'כיכר הקתדרלה' }, en: { name: 'Cathedral Square' } },
  { id: 'old-town', region: 'vilnius', he: { name: 'העיר העתיקה' }, en: { name: 'Old Town' } },
  { id: 'trakai-castle', region: 'trakai', he: { name: 'טירת טראקאי' }, en: { name: 'Trakai Castle' } },
  { id: 'laisves', region: 'kaunas', he: { name: 'שדרת Laisvės' }, en: { name: 'Laisvės Alėja' } },
  { id: 'ninth-fort', region: 'kaunas', he: { name: 'הפורט התשיעי' }, en: { name: 'Ninth Fort' } },
  { id: 'theatre-square', region: 'klaipeda', he: { name: 'כיכר התיאטרון' }, en: { name: 'Theatre Square' } },
  { id: 'palanga', region: 'klaipeda', he: { name: 'פלאנגה' }, en: { name: 'Palanga' } },
  { id: 'parnidis', region: 'curonian', he: { name: 'דיונת פרנידיס' }, en: { name: 'Parnidis Dune' } },
  { id: 'thomas-mann', region: 'curonian', he: { name: 'בית תומאס מאן' }, en: { name: 'Thomas Mann House' } }
];

// Traditional dishes (separate from Niv venues)
const DISHES = [
  { id: 'saltibarsciai', emoji: '🍲', liquid: '#f48fb1', spoon: true, bg: 'linear-gradient(135deg, #e91e6332, #f48fb150)', he: { name: 'שלטיברשצ\'יי', desc: 'מרק סלק קר ורוד-זוהר עם קפיר וביצה קשה. הקיץ במנה.', tag: 'קלאסי' }, en: { name: 'Šaltibarščiai', desc: 'Glowing pink cold beet soup with kefir and boiled egg. Summer in a bowl.', tag: 'Classic' }, ph: 'Bright pink cold soup' },
  { id: 'cepelinai', emoji: '🥟', bg: 'linear-gradient(135deg, #a0522d28, #d4a56830)', he: { name: 'צפלינאי', desc: 'כופתאות תפוח-אדמה גדולות במילוי בשר עם רוטב שמנת ובייקון.', tag: 'מסורתי' }, en: { name: 'Cepelinai', desc: 'Zeppelin-shaped potato dumplings stuffed with meat, cream & bacon.', tag: 'Traditional' }, ph: 'Two potato dumplings on plate' },
  { id: 'kibinai', emoji: '🥐', bg: 'linear-gradient(135deg, #c8960028, #fdd83530)', he: { name: 'קיביני', desc: 'מאפי בצק קראימיים במילוי כבש או גבינה. הכי טוב בטראקאי.', tag: 'טראקאי' }, en: { name: 'Kibinai', desc: 'Karaim hand pies filled with mutton or cheese. Best in Trakai.', tag: 'Trakai' }, ph: 'Golden half-moon pastries' },
  { id: 'kepta-duona', emoji: '🍞', bg: 'linear-gradient(135deg, #3d2b1a30, #6b4c3228)', he: { name: 'קפטא-דונה', desc: 'אצבעות לחם שיפון מטוגנות עם שום. חברה הכי טובה של בירה.', tag: 'נשנוש' }, en: { name: 'Kepta Duona', desc: 'Fried rye bread sticks with garlic. Beer\'s best friend.', tag: 'Snack' }, ph: 'Dark rye toast sticks' },
  { id: 'sakotis', emoji: '🍰', bg: 'linear-gradient(135deg, #f59e0b28, #fef08a30)', he: { name: 'שאקוטיס', desc: 'עוגת "עץ" צהבהבה עם זיזים, נאפית על שיפוד מסתובב.', tag: 'מתוק' }, en: { name: 'Šakotis', desc: 'Spiky golden "tree cake" baked on a rotating spit.', tag: 'Sweet' }, ph: 'Spiky golden tree cake' }
];

const ITINERARIES = [
  {
    id: 'vilnius-day',
    duration: 'day',
    region: 'vilnius',
    he: { title: 'יום מושלם בווילנה', tagline: 'מסמטאות הברוק עד אוז\'ופיס' },
    en: { title: 'A Perfect Day in Vilnius', tagline: 'From Baroque alleys to Užupis' },
    stops: [
      { time: '09:00', placeId: 'backstage-roastery-caf', landmarkId: null, he: 'ברנץ\' ב-Backstage', en: 'Brunch at Backstage' },
      { time: '11:00', placeId: null, landmarkId: 'cathedral', he: 'כיכר הקתדרלה', en: 'Cathedral Square' },
      { time: '12:00', placeId: null, landmarkId: 'gediminas', he: 'עלייה למגדל גדימינאס', en: 'Climb Gediminas Tower' },
      { time: '13:30', placeId: '2-vir-jai', landmarkId: null, he: 'צהריים ב-2 Virėjai — אוכל ליטאי אמיתי', en: 'Lunch at 2 virėjai — honest Lithuanian food' },
      { time: '15:00', placeId: null, landmarkId: 'uzupis', he: 'מעבר לרפובליקת אוז\'ופיס', en: 'Cross into Užupis' },
      { time: '17:00', placeId: 'mo-museum', landmarkId: null, he: 'אמנות מודרנית במוזיאון MO', en: 'Modern art at MO Museum' },
      { time: '19:30', placeId: 'barn-bistro-b-arn', landmarkId: null, he: 'ארוחת ערב חגיגית ב-BARN', en: 'Celebratory dinner at BARN' },
      { time: '22:00', placeId: '3m-zos-rooftop-bar', landmarkId: null, he: 'כוסית בגג', en: 'Rooftop drink' }
    ]
  },
  {
    id: 'baltic-week',
    duration: 'weekend',
    region: null,
    he: { title: 'וילנה והסביבה', tagline: 'יום בעיר, יום בטבע' },
    en: { title: 'Vilnius & The Region', tagline: 'A day in the city, a day in nature' },
    stops: [
      { time: 'יום 1', timeEn: 'Day 1', placeId: 'mo-museum', landmarkId: null, he: 'וילנה: מוזיאון MO ואומנות רחוב באוז\'ופיס', en: 'Vilnius: MO Museum & Užupis street art walk' },
      { time: 'יום 2 בוקר', timeEn: 'Day 2 morning', placeId: 'snapas-kava-ir-desertai', landmarkId: null, he: 'טראקאי — קפה ומאפה ב-Snapas', en: 'Trakai — coffee & pastry at Snapas' },
      { time: 'יום 2 צהריים', timeEn: 'Day 2', placeId: null, landmarkId: 'trakai-castle', he: 'טירת טראקאי + צהריים ב-Kiubėtė על האגם', en: 'Trakai Castle + lunch at Kiubėtė on the lake' },
      { time: 'יום 2 אחה"צ', timeEn: 'Day 2 afternoon', placeId: 'trakai-balloon-ride', landmarkId: null, he: 'כדור פורח מעל הטירה והאגמים', en: 'Hot air balloon over the castle & lakes' }
    ]
  },
  {
    id: 'forest-weekend',
    duration: 'weekend',
    region: 'countryside',
    he: { title: 'סופ"ש ביערות', tagline: 'אגמים, בקתות, וסאונה' },
    en: { title: 'A Weekend in the Forests', tagline: 'Lakes, cabins, and sauna' },
    stops: [
      { time: 'שישי–שבת', timeEn: 'Fri–Sat', placeId: 'varena-treehouse', landmarkId: null, he: 'בית-עץ ביער', en: 'Cabin in the trees' },
      { time: 'שבת–ראשון', timeEn: 'Sat–Sun', placeId: 'villa-the-lake', landmarkId: null, he: 'וילה על האגם', en: 'Villa by the lake' }
    ]
  },
  {
    id: 'coast-3day',
    duration: 'short',
    region: 'klaipeda',
    he: { title: 'שלושה ימים על החוף', tagline: 'נמל, דיונות, וספא' },
    en: { title: 'Three Days on the Coast', tagline: 'Port, dunes, and spa' },
    stops: [
      { time: 'יום 1', timeEn: 'Day 1', placeId: 'kavos-architektai', landmarkId: null, he: 'קפה בוקר בעיר הישנה', en: 'Morning coffee in the old town' },
      { time: 'יום 1', timeEn: 'Day 1', placeId: 'klaipeda-old-town-walk', landmarkId: null, he: 'סמטאות פרוסיות, חצרות נסתרות ואמנות רחוב', en: 'Prussian lanes, hidden courtyards & street art' },
      { time: 'יום 1 ערב', timeEn: 'Day 1 eve', placeId: 'ateik-ateik', landmarkId: null, he: 'שקיעה על הנמל עם ג\'אז וספינות יוצאות', en: 'Sunset at the port — jazz, ships & cold beer' },
      { time: 'יום 2', timeEn: 'Day 2', placeId: 'the-dead-dunes', landmarkId: null, he: 'מעבורת לנידה: עלייה על הדיונה הגדולה', en: 'Ferry to Nida — climb the Great Dune' },
      { time: 'יום 2 ערב', timeEn: 'Day 2 eve', placeId: 'nida-harbour', landmarkId: null, he: 'נמל נידה: סירות צבעוניות ושקיעה על הלגון', en: 'Nida harbour — colourful boats & lagoon sunset' },
      { time: 'יום 3', timeEn: 'Day 3', placeId: 'stebuklai-spa', landmarkId: null, he: 'ספא יוקרתי בנידה — בריכות, שקט, ויערות אורן', en: 'Stebuklai SPA — pools, silence & pine forest' }
    ]
  },
  {
    id: 'spa-weekend',
    duration: 'weekend',
    region: 'druskininkai',
    he: { title: 'סוף שבוע ספא בדרוסקיניינקאי', tagline: 'מעיינות, ספא, ויערות אורן' },
    en: { title: 'Druskininkai Spa Weekend', tagline: 'Springs, spa, and pine forests' },
    stops: [
      { time: 'שישי אחה"צ', timeEn: 'Friday afternoon', placeId: 'mana-sleep-spa-druskininkai', landmarkId: null, he: 'הגעה למאנה ספא — מרחץ מינרלים ערב', en: 'Arrive at Mana & evening mineral spring bath' },
      { time: 'שבת בוקר', timeEn: 'Saturday morning', placeId: 'mana-sleep-spa-druskininkai', landmarkId: null, he: 'טיפול פלואוטינג וחדר מלח ים המלח', en: 'Float therapy & Dead Sea salt room' },
      { time: 'שבת אחה"צ', timeEn: 'Saturday afternoon', placeId: 'grutas-park', landmarkId: null, he: 'טיול קצר בעיר ופארק גרוטס', en: 'City stroll & Grūtas Park' },
      { time: 'שבת ערב', timeEn: 'Saturday evening', placeId: 'toli-toli-druskininkai', landmarkId: null, he: 'ארוחת ערב במסעדת טולי טולי', en: 'Dinner at Toli Toli' },
      { time: 'ראשון', timeEn: 'Sunday', placeId: 'mana-sleep-spa-druskininkai', landmarkId: null, he: 'טיפול ספא אחרון — עיסוי ובריכה תרמית לפני יציאה', en: 'Final treatment — massage & thermal pool before checkout' }
    ]
  }
];

const FACTS = [
  { he: 'ליטא היא המדינה הראשונה שהכריזה על עצמאות מברה"מ — 1990.', en: 'Lithuania was the first to declare independence from the USSR — 1990.' },
  { he: '90% משיווק העולמי של ענבר בלטי עובר דרך ליטא.', en: '90% of the world\'s Baltic amber passes through Lithuania.' },
  { he: 'הליטאית היא אחת השפות הארכאיות החיות באירופה.', en: 'Lithuanian is one of the most archaic living languages in Europe.' },
  { he: 'יש כאן יותר מ-3,000 אגמים. כן, באמת.', en: 'There are over 3,000 lakes here. Yes, really.' },
  { he: 'אוז\'ופיס היא "רפובליקה" עם נשיא, חוקה וצבא של 11 איש.', en: 'Užupis is a "republic" with a president, constitution, and an army of 11.' },
  { he: 'המרכז הגיאוגרפי של אירופה — מצפון לווילנה.', en: 'The geographic center of Europe is just north of Vilnius.' },
  { he: '50% מליטא מכוסה ביערות. הריח של אורן הוא הריח של החופש.', en: 'Half of Lithuania is forest. Pine smell = freedom.' }
];

const MAP_URL = 'https://maps.app.goo.gl/JcnKq69fj1RMw1RL7';

window.LT_DATA = { REGIONS, PLACES, LANDMARKS, DISHES, ITINERARIES, FACTS, MAP_URL };

})();
